version: "3.9"

services:
  web:
    container_name: web
    build: .
    environment:
      DATABASE_URL: "host=db user=user password=password dbname=postgres sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
